// ================= CONSTANTS =================

export const BENTUK_KEGIATAN_OPTIONS = [
  "-Pilih-",
  "Pendidikan",
  "Penelitian",
  "Pengabdian Masyarakat",
  "Pelatihan",
];

export const SASARAN_OPTIONS = ["-Pilih-", "Mahasiswa", "Dosen", "Masyarakat"];

export const INDIKATOR_OPTIONS = ["-Pilih-", "Output", "Outcome", "Impact"];

export const STATUS_DOKUMEN_OPTIONS = [
  { label: "Aktif", value: "Aktif" },
  { label: "Kadaluarsa", value: "Kadaluarsa" },
  { label: "Dalam Perpanjangan", value: "DalamPerpanjangan" },
  { label: "Tidak Aktif", value: "TidakAktif" },
];

export const JENIS_DOKUMEN_OPTIONS = [
  { label: "MoU (Memorandum of Understanding)", value: "MOU" },
  { label: "MoA (Memorandum of Agreement)", value: "MOA" },
  { label: "IA (Implementation Arrangement)", value: "IA" },
];

export const SKALA_KERJASAMA_OPTIONS = ["-Pilih-", "Nasional", "Internasional"];

export const SUMBER_PENDANAAN_OPTIONS = [
  "-Pilih-",
  "Direktorat PSD",
  "Direktorat PSMP",
  "Direktorat PSMA",
  "Direktorat PSMK",
  "Direktorat PKLK Dikdas",
  "Direktorat PKLK Dikmen",
  "Direktorat P2TK Dikdas",
  "Direktorat P2TK Dikmen",
  "Sekretariat Dikdas",
  "Sekretariat Dikmen",
  "Biro PKLN",
  "Pustekkom",
  "Puskurbuk",
  "Puspendik",
  "Balitbang",
  "Badan PSDMPK dan PMP",
  "Dikti",
  "Dinas Propinsi",
  "Dinas Kabupaten",
  "DIPA PTN",
  "DP2M Ristekdikti",
  "Insinas Ristekdikti",
  "Lembaga donor dalam negeri",
  "Lembaga donor luar negeri",
  "Dana mandiri",
  "Bantuan Swasta",
  "Bantuan Asing",
  "Lainnya",
];

export const UNIT_PENANGGUNG_JAWAB_OPTIONS = [
  "-Pilih-",
  "Biro Akademik dan Kemahasiswaan",
  "Biro Umum dan Keuangan",
  "Biro Perencanaan dan Hubungan Masyarakat",
  "Fakultas Ekonomi dan Bisnis",
  "Fakultas Hukum",
  "Fakultas Keguruan dan Ilmu Pendidikan",
  "Fakultas Pertanian",
  "Fakultas Teknik",
  "Fakultas Ilmu Sosial dan Ilmu Politik",
  "Fakultas Matematika dan Ilmu Pengetahuan Alam",
  "Fakultas Kedokteran",
  "Pascasarjana",
  "Lembaga Penelitian dan Pengabdian kepada Masyarakat",
  "Lembaga Pengembangan Pembelajaran dan Penjaminan Mutu",
  "UPT Perpustakaan",
  "UPT Teknologi Informasi dan Komunikasi",
  "UPT Laboratorium Terpadu dan Sentra Inovasi Teknologi",
  "UPT Bahasa",
  "UPT Pengembangan Karir dan Kewirausahaan",
  "UPT Pengembangan Kerjasama dan Layanan Internasional",
  "Badan Pengelola Usaha",
  "UPT Kearsipan",
  "Satuan Pengendalian Internal",
  "Senat Unila",
];

export const BIDANG_USAHA_OPTIONS = [
  "-Pilih-",
  "Pertanian, Kehutanan, dan Perikanan",
  "Pertambangan dan Penggalian",
  "Industri Pengolahan",
  "Listrik, Gas, dan Listrik Air Bersih",
  "Pengelolaan Air Limbah dan Remediasi",
  "Konstruksi dan Perdagangan",
  "Pengangkutan dan Pergudangan",
  "Informasi dan Komunikasi",
  "Aktivitas Keuangan dan Asuransi",
  "Real Estat",
  "Pendidikan, Kesehatan, dan Sosial",
  "Kesenian dan Hiburan",
];

export const NEGARA_OPTIONS = [
  "-Pilih-",
  "Afghanistan",
  "Albania",
  "Aljazair",
  "Amerika Serikat",
  "Andorra",
  "Angola",
  "Antigua dan Barbuda",
  "Arab Saudi",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahama",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belanda",
  "Belarus",
  "Belgia",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia dan Herzegovina",
  "Botswana",
  "Brasil",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Chad",
  "Chili",
  "China",
  "Denmark",
  "Dominika",
  "Ekuador",
  "El Salvador",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Filipina",
  "Finlandia",
  "Gabon",
  "Gambia",
  "Georgia",
  "Ghana",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea Khatulistiwa",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hongaria",
  "India",
  "Indonesia",
  "Inggris",
  "Irak",
  "Iran",
  "Irlandia",
  "Islandia",
  "Israel",
  "Italia",
  "Jamaika",
  "Jepang",
  "Jerman",
  "Kamboja",
  "Kamerun",
  "Kanada",
  "Kazakhstan",
  "Kenya",
  "Kirgizstan",
  "Kiribati",
  "Kolombia",
  "Komoro",
  "Kongo",
  "Korea Selatan",
  "Korea Utara",
  "Kosta Rika",
  "Kroasia",
  "Kuba",
  "Kuwait",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lituania",
  "Luksemburg",
  "Madagaskar",
  "Maladewa",
  "Malawi",
  "Malaysia",
  "Mali",
  "Malta",
  "Maroko",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Meksiko",
  "Mesir",
  "Mikronesia",
  "Moldova",
  "Monako",
  "Mongolia",
  "Montenegro",
  "Mozambik",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Niger",
  "Nigeria",
  "Norwegia",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua Nugini",
  "Paraguay",
  "Peru",
  "Polandia",
  "Portugal",
  "Qatar",
  "Republik Afrika Tengah",
  "Republik Ceko",
  "Republik Dominika",
  "Rumania",
  "Rusia",
  "Rwanda",
  "Saint Kitts dan Nevis",
  "Saint Lucia",
  "Saint Vincent dan Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome dan Principe",
  "Selandia Baru",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapura",
  "Siprus",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "Spanyol",
  "Sri Lanka",
  "Sudan",
  "Sudan Selatan",
  "Suriah",
  "Swedia",
  "Swiss",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor Leste",
  "Togo",
  "Tonga",
  "Trinidad dan Tobago",
  "Tunisia",
  "Turki",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraina",
  "Uni Emirat Arab",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatikan",
  "Venezuela",
  "Vietnam",
  "Yaman",
  "Yordania",
  "Yunani",
  "Zambia",
  "Zimbabwe",
];

export const KLASIFIKASI_MITRA_OPTIONS = [
  "-Pilih-",
  "IKU - Perusahaan multinasional",
  "IKU - Perusahaan nasional berstandar tinggi",
  "IKU - Perusahaan teknologi global",
  "IKU - Perusahaan rintisan (startup company) teknologi",
  "IKU - Organisasi nirlaba kelas dunia",
  "IKU - Institusi/ Organisasi multilateral",
  "IKU - Instansi pemerintah, BUMN dan/atau BUMD",
  "IKU - Rumah Sakit",
  "IKU - UMKM",
  "IKU - Perguruan tinggi, fakultas, atau program studi dalam bidang yang relevan",
  "IKU - Institusi Pendidikan",
  "IKU - Organisasi",
  "NON IKU - Pemerintah Provinsi dan Kabupaten/Kota",
  "IKU - Perguruan tinggi yang masuk dalam daftar QS200",
  "IKU - Lembaga riset pemerintah, swasta, nasional maupun internasional",
  "IKU - Lembaga kebudayaan berskala nasional/bereputasi",
];

export const BULAN_OPTIONS = [
  "Januari",
  "Februari",
  "Maret",
  "April",
  "Mei",
  "Juni",
  "Juli",
  "Agustus",
  "September",
  "Oktober",
  "November",
  "Desember",
];
